BooksFair/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BooksFair.DataAccess.Repository;
using BooksFair.DataAccess.Repository.IRepository;
using BooksFair.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace BooksFair.Areas.Admin.Controllers {
    [Area("Admin")]
    public class CategoryController : Controller {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryController(IUnitOfWork unitOfWork) {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index() {
            return View();
        }

        public IActionResult Upsert(int? id) {
            Category category = new Category();
            if ( id == null )
                return View(category);

            category = _unitOfWork.Category.Get(id.GetValueOrDefault());//protect from null

            if ( category == null )
                return NotFound();

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Category category) {
            if (!ModelState.IsValid) {
                return View(category);
            }

            if ( category.Id == 0 )
                _unitOfWork.Category.Add(category);
            else
                _unitOfWork.Category.Update(category);

            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

        #region API CALLS
        [HttpGet]
        public IActionResult GetAll() {
            var allObj = _unitOfWork.Category.GetAll();
            return Json(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id) {
            if(id == 0)
                return NotFound(new { success = false, message = "Id can't be null" });

            var objFromDb = _unitOfWork.Category.Get(id);

            if ( objFromDb == null ) {
                return NotFound(new { success = false, message = "Object for delete isn't found" });
            }

            _unitOfWork.Category.Remove(objFromDb);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }
        #endregion
    }
}

BooksFair/Areas/Admin/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BooksFair.DataAccess.Repository;
using BooksFair.DataAccess.Repository.IRepository;
using BooksFair.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace BooksFair.Areas.Admin.Controllers {
    [Area("Admin")]
    public class CompanyController : Controller {
        private readonly IUnitOfWork _unitOfWork;

        public CompanyController(IUnitOfWork unitOfWork) {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index() {
            return View();
        }

        public IActionResult Upsert(int? id) {
            Company company = new Company();
            if ( id == null )
                return View(company);

            company = _unitOfWork.Company.Get(id.GetValueOrDefault());//protect from null

            if ( company == null )
                return NotFound();

            return View(company);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(Company company) {
            if (!ModelState.IsValid) {
                return View(company);
            }

            if ( company.Id == 0 )
                _unitOfWork.Company.Add(company);
            else
                _unitOfWork.Company.Update(company);

            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll() {
            var allObj = _unitOfWork.Company.GetAll();
            return Ok(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id) {
            if(id == 0)
                return NotFound(new { success = false, message = "Id can't be null" });

            var objFromDb = _unitOfWork.Company.Get(id);

            if ( objFromDb == null ) {
                return NotFound(new { success = false, message = "Object for delete doesn't found" });
            }

            _unitOfWork.Company.Remove(objFromDb);
            _unitOfWork.Save();
            return Ok(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

BooksFair/Areas/Admin/Controllers/CoverTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BooksFair.DataAccess.Repository.IRepository;
using BooksFair.Models;
using BooksFair.Utility;
using Dapper;
using Microsoft.AspNetCore.Mvc;

namespace BooksFair.Areas.Admin.Controllers {
    [Area("Admin")]
    public class CoverTypeController : Controller {
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork) {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index() {
            return View();
        }

        public IActionResult Upsert(int? id) {
            var coverType = new CoverType();
            if ( id == null )
                return View(coverType);

            var parameter = new DynamicParameters();
            parameter.Add("@Id", id);

            coverType = _unitOfWork.SPCall.OneRecord<CoverType>(SD.ProcCoverTypeGet, parameter);

            if ( coverType == null )
                return NotFound();

            return View(coverType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(CoverType coverType) {
            if ( !ModelState.IsValid ) {
                return View(coverType);
            }

            var parameter = new DynamicParameters();
            parameter.Add("@Name", coverType.Name);

            if ( coverType.Id == 0 ) {
                _unitOfWork.SPCall.Execute(SD.ProcCoverTypeCreate, parameter);
            } else {
                parameter.Add("@Id", coverType.Id);
                _unitOfWork.SPCall.Execute(SD.ProcCoverTypeUpdate, parameter);
            }

            return RedirectToAction(nameof(Index));
        }


        #region API CALLS

        [HttpGet]
        public IActionResult GetAll() {
            var allObj = _unitOfWork.SPCall.List<CoverType>(SD.ProcCoverTypeGetAll);
            return Ok(new { data = allObj });
        }

        [HttpDelete]
        public IActionResult Delete(int id) {
            if ( id == 0 )
                return NotFound(new { success = false, message = "Id can't be null" });

            var parameter = new DynamicParameters();
            parameter.Add("@Id", id);
            object test = new { id }; //test anonymous type

            var objFromDb = _unitOfWork.SPCall.OneRecord<CoverType>(SD.ProcCoverTypeGet, parameter);

            if ( objFromDb == null )
                return NotFound(new { success = false, message = "Object for delete doesn't found" });

            _unitOfWork.SPCall.Execute(SD.ProcCoverTypeDelete, test);

            return Ok(new { success = true, message = "Delete Successful" });
        }

        #endregion
    }
}

BooksFair/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BooksFair.DataAccess.Repository;
using BooksFair.DataAccess.Repository.IRepository;
using BooksFair.Models;
using BooksFair.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;


namespace BooksFair.Areas.Admin.Controllers {
    [Area("Admin")]
    public class ProductController : Controller {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _hostEnviroment; //for upload images

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment hostEnvironment) {
            _unitOfWork = unitOfWork;
            _hostEnviroment = hostEnvironment;
        }
        public IActionResult Index() {
            return View();
        }

        public IActionResult Upsert(int? id) {
            ProductVM productVM = new ProductVM() {
                Product = new Product(),
                CategoryList = _unitOfWork.Category.GetAll().Select(c => new SelectListItem {
                    Text = c.Name, //convert item to option in HTML
                    Value = c.Id.ToString()
                }),
                CoverTypeList = _unitOfWork.CoverType.GetAll().Select(c => new SelectListItem {
                    Text = c.Name, //convert item to option in HTML
                    Value = c.Id.ToString()
                })
            };

            if ( id == null ) {
                productVM.Product.ImageUrl = "empty";
                return View(productVM);
            }

            productVM.Product = _unitOfWork.Product.Get(id.GetValueOrDefault());

            if ( productVM.Product == null )
                return NotFound();
            return View(productVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ProductVM productVM) {
            if ( !ModelState.IsValid ) {
                productVM.CategoryList = _unitOfWork.Category.GetAll().Select(c => new SelectListItem {
                    Text = c.Name, //convert item to option in HTML
                    Value = c.Id.ToString()
                });
                productVM.CoverTypeList = _unitOfWork.CoverType.GetAll().Select(c => new SelectListItem {
                    Text = c.Name, //convert item to option in HTML
                    Value = c.Id.ToString()
                });
                return View(productVM);
            }

            string webRootPath = _hostEnviroment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            if ( files.Count > 0 ) {
                string fileName = Guid.NewGuid().ToString(); //Globally Unique Identifier
                var uploads = Path.Combine(webRootPath, @"images\products\");
                var extenstion = Path.GetExtension(files[0].FileName);

                if ( productVM.Product.ImageUrl != "empty" ) { //don't fulling with file attach
                    //this is an edit and we need to remove old image
                    var objFromDb = _unitOfWork.Product.Get(productVM.Product.Id); //to protect from fake file path

                    DeleteIMGfromProduct(objFromDb);
                }

                using ( var filesStream = new FileStream(Path.Combine(uploads, fileName + extenstion), FileMode.Create) ) {
                    files[0].CopyTo(filesStream);
                }

                productVM.Product.ImageUrl = @"\images\products\" + fileName + extenstion;

            } else if ( productVM.Product.Id != 0 ) {
                var objFromDb = _unitOfWork.Product.Get(productVM.Product.Id);

                productVM.Product.ImageUrl = objFromDb.ImageUrl; //to protect from fake file path
            }

            if ( productVM.Product.Id == 0 )
                _unitOfWork.Product.Add(productVM.Product);
            else
                _unitOfWork.Product.Update(productVM.Product);

            _unitOfWork.Save();

            return RedirectToAction(nameof(Index));
        }

        #region API CALLS

        // GET: Admin/Product/GetAll
        [HttpGet]
        public IActionResult GetAll() {
            var allObj = _unitOfWork.Product.GetAll(includeProperties: $"{nameof(Category)},{nameof(CoverType)}");
            return Ok(new { data = allObj });
        }

        // POST: Admin/Product/Delete
        [HttpDelete]
        public IActionResult Delete(int id) {
            if ( id == 0 )
                return NotFound(new { success = false, message = "Id can't be null" });

            var objFromDb = _unitOfWork.Product.Get(id);

            if ( objFromDb == null ) {
                return NotFound(new { success = false, message = "Object for delete doesn't found" });
            }

            DeleteIMGfromProduct(objFromDb);

            _unitOfWork.Product.Remove(objFromDb);
            _unitOfWork.Save();
            return Ok(new { success = true, message = "Delete Successful" });
        }

        #endregion

        private void DeleteIMGfromProduct(Product product) {
            var imagePath = Path.Combine(_hostEnviroment.WebRootPath, product.ImageUrl.TrimStart('\\'));
            if ( System.IO.File.Exists(imagePath) ) {
                System.IO.File.Delete(imagePath);
            }
        }
    }
}

BooksFair/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row buttons-group-create-back">
    <div class="col">
        <button type="submit" id="createBtn" class="btn btn-primary">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>
</div>

BooksFair/Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row buttons-group-create-back">
    <div class="col">
        <button type="submit" class="btn btn-primary" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <button asp-action="Index" class="btn btn-success">Back to List</button>
    </div>
</div>

BooksFair/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BooksFair</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    @*<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />*@
    <link rel="stylesheet" href="~/lib/DataTables/datatables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        @*style="position:fixed; z-index:5"*@
        <nav class="navbar navbar-expand-sm flex-column navbar-dark bg-primary border-bottom box-shadow mb-3 pb-0 pt-1">
            <div class="container h6">
                <a class="navbar-brand mt-2" style="height: 40px; width:35px"asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-book-open font-weight-bold h3"></i> 
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="CoverType" asp-action="Index">Cover Type</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Company / User
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50 bg-primary">
        <div class="container">
            &copy; 2020 - BooksFair
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    @*<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>*@
    <script src="~/lib/DataTables/datatables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>